// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/auto-translate.mjs
// Run: pnpm translate

import en from './en.json';

// Define all supported languages
export type Language = 
  | 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'ja' | 'zh' | 'ko'
  | 'ar' | 'hi' | 'bn' | 'ur' | 'fa' | 'tr' | 'pl' | 'uk' | 'ro' | 'nl'
  | 'sv' | 'no' | 'da' | 'fi' | 'cs' | 'hu' | 'el' | 'he' | 'th' | 'vi'
  | 'id' | 'ms' | 'tl' | 'sk' | 'sl' | 'bg' | 'hr' | 'sr' | 'et' | 'lt'
  | 'lv' | 'mk' | 'sq' | 'hy' | 'ka' | 'kk' | 'uz' | 'ta' | 'te' | 'ml'
  | 'kn' | 'gu' | 'mr' | 'pa' | 'my' | 'km' | 'lo' | 'am' | 'sw';

// Resources object - will be populated by auto-translate script
export const resources: Record<Language, any> = {
  'en': en,
} as Record<Language, any>;

export const languageNames: Record<Language, string> = {
  'en': 'English',
  'es': 'Español',
  'fr': 'Français',
  'de': 'Deutsch',
  'it': 'Italiano',
  'pt': 'Português',
  'ru': 'Русский',
  'ja': '日本語',
  'zh': '中文',
  'ko': '한국어',
  'ar': 'العربية',
  'hi': 'हिन्दी',
  'bn': 'বাংলা',
  'ur': 'اردو',
  'fa': 'فارسی',
  'tr': 'Türkçe',
  'pl': 'Polski',
  'uk': 'Українська',
  'ro': 'Română',
  'nl': 'Nederlands',
  'sv': 'Svenska',
  'no': 'Norsk',
  'da': 'Dansk',
  'fi': 'Suomi',
  'cs': 'Čeština',
  'hu': 'Magyar',
  'el': 'Ελληνικά',
  'he': 'עברית',
  'th': 'ไทย',
  'vi': 'Tiếng Việt',
  'id': 'Bahasa Indonesia',
  'ms': 'Bahasa Melayu',
  'tl': 'Tagalog',
  'sk': 'Slovenčina',
  'sl': 'Slovenščina',
  'bg': 'Български',
  'hr': 'Hrvatski',
  'sr': 'Српски',
  'et': 'Eesti',
  'lt': 'Lietuvių',
  'lv': 'Latvian',
  'mk': 'Македонски',
  'sq': 'Shqip',
  'hy': 'Հայերեն',
  'ka': 'ქართული',
  'kk': 'Қазақ',
  'uz': 'Ўзбек',
  'ta': 'தமிழ்',
  'te': 'తెలుగు',
  'ml': 'മലയാളം',
  'kn': 'ಕನ್ನಡ',
  'gu': 'ગુજરાતી',
  'mr': 'मराठी',
  'pa': 'ਪੰਜਾਬੀ',
  'my': 'မြန်မာ',
  'km': 'ខ្មែរ',
  'lo': 'ລາວ',
  'am': 'አማርኛ',
  'sw': 'Kiswahili'
};

export const rtlLanguages: Language[] = ['ar', 'ur', 'fa', 'he'] as unknown as Language[];

export function getLanguageName(lang: Language): string {
  return languageNames[lang] || lang;
}

export function isRTL(lang: Language): boolean {
  return rtlLanguages.includes(lang);
}
